- name: Prepare stand
  hosts: all
  become: yes
  tasks:

  - name: install docker dependencies
    apt:
      name: "{{ item }}"
      state: present
      update_cache: yes
    loop:
      - acl
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

  - name: addd dDocker GPG apt key
    become: true
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: add docker repository
    become: true
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu jammy stable
      state: present

  - name: install docker
    apt:
      name: "{{ item }}"
      state: latest
      update_cache: yes
    loop:
      - docker
      - docker-ce
      - docker-compose

  - name: check if docker enabled
    become: true
    service:
      name: docker
      state: started
      enabled: true

  - name: create stand user
    user:
      name: crab-stand
      home: /home/crab-stand
      groups: docker
      append: yes

  - name: create services dir
    ansible.builtin.file:
      path: /home/crab-stand/services
      state: directory
      owner: crab-stand
