- name: Prepare stand
  hosts: all
  become: yes
  tasks:

  - name: install docker dependencies
    apt:
      name: "{{ item }}"
      state: present
      update_cache: yes
    loop:
      - acl
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

  - name: addd dDocker GPG apt key
    become: true
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: add docker repository
    become: true
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu jammy stable
      state: present

  - name: install docker
    apt:
      name: "{{ item }}"
      state: latest
      update_cache: yes
    loop:
      - docker
      - docker-ce
      - docker-compose

  - name: check if docker enabled
    become: true
    service:
      name: docker
      state: started
      enabled: true

  - name: create stand user
    user:
      name: crab-stand
      home: /home/crab-stand
      groups: docker
      append: yes
  
  - name: set up ssh key
    ansible.posix.authorized_key:
      user: crab-stand
      state: present
      key: "{{ lookup('file', '/crab/ansible/kostyl-key.pub') }}"

  - name: create services dir
    ansible.builtin.file:
      path: /home/crab-stand/services
      state: directory
      owner: crab-stand

  - name: create directory for docker service override
    file:
      path: /etc/systemd/system/docker.service.d
      state: directory

  - name: create clear file override.conf
    copy:
      content: ""
      dest: /etc/systemd/system/docker.service.d/override.conf
      force: false
      group: sys
      owner: root
      mode: 0555

  - name: write override.conf file
    blockinfile:
      path: /etc/systemd/system/docker.service.d/override.conf
      block: |
        [Service]
        ExecStart=
        ExecStart=/usr/bin/dockerd -H fd:// -H tcp://0.0.0.0:2376

  - name: reload systemd daemon
    systemd:
      daemon_reload: yes

  - name: restart Docker service
    systemd:
      name: docker.service
      state: restarted
