services:
  backend:
    container_name: crab-back
    build: backend/
    ports:
      - 8080:8080
    environment:
      DB_HOST: dbpostgresql
      DB_PORT: 5432
    depends_on:
      - dbpostgresql

  dbpostgresql:
    container_name: dbpostgresql
    image: postgres
    ports:
      - 5434:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: crab
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U postgres -d crab"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  frontend:
    container_name: crab-front
    build: frontend/
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
