services:
  backend:
    container_name: crab-back
    build: backend/
    ports:
      - 8080:8080
    depends_on:
      - dbpostgresql
  dbpostgresql:
    container_name: 'dbpostgresql'
    image: 'postgres'
    ports:
      - 5434:5432
    environment:
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_DB=crab'
    volumes:
      - ./postgres-data:/var/lib/postgresql/postgres-data
