spring:
    application:
        name: crab
    datasource:
        url: 'jdbc:postgresql://${DB_HOST}:${DB_PORT}/crab'
        username: postgres
        password: password
        driverClassName: org.postgresql.Driver
    liquibase:
        change-log: classpath:db/changelog/db.changelog-master.yml
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
